name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install git-crypt
        run: |
          git clone https://github.com/AGWA/git-crypt.git
          cd git-crypt && make && make install PREFIX=/opt/project
          echo "/opt/project/bin" >> $GITHUB_PATH
      - name: Unlock git-crypt
        shell: bash
        env:
          git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$git_crypt_key" | base64  -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Add heroku remote repo
        run: git remote add heroku https://git.heroku.com/food-blog-proof-of-concept.git

      - name: Deploy to Heroku
        run: git push heroku main 
