name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install git-crypt
      - name: Install git-crypt
        run: |
          git clone https://github.com/AGWA/git-crypt.git
          cd git-crypt && make && make install PREFIX=/opt/project
          echo "/opt/project/bin" >> $GITHUB_PATH

      # Unlock repository
      - name: Unlock git-crypt
        shell: bash
        env:
          git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$git_crypt_key" | base64  -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      # Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        env:
          HD_NODE_ENV: 'production'
          HD_HOST: https://food-blog-proof-of-concept.herokuapp.com/
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'food-blog-proof-of-concept'
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
          buildpack: 'https://github.com/heroku/heroku-buildpack-nodejs#latest'
