name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Additional steps
        run: less ./private/test.json

      # Deploy to Heroku
      - name: Deploy to Heroku
        env:
          HD_NODE_ENV: 'production'
        uses: CDNievas/heroku-action@v1.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'food-blog-proof-of-concept'
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
          buildpacks: "['https://github.com/heroku/heroku-buildpack-nodejs.git']"
